### ISSUE TITLE
How to use this lib in swift?

### ISSUE THREAD

**Issue by aldolazuardi** [OceanLabs/InstagramImagePicker-iOS#10]
i'm successfully implement OLFacebookImagePicker-iOS in swift. Now im trying to use InstagramImagePicker-iOS in swift with same method, but when i put OLInstagramPickerControllerDelegate it shows "use of undeclared type 'OLInstagramImagePickerControlerDelegate'". Does this lib support swift?

**Comment by aldolazuardi** [comment]
turns out i forgot to put "import InstagramImagePicker" in view controller

**Comment by ravirajm** [comment]
hi would it be possible for you to explain how you implemented it using swift?
