### ISSUE TITLE
Redirect URI

### ISSUE THREAD

**Issue by tahirsohaib** [OceanLabs/InstagramImagePicker-iOS#14]
@kkarayannis, As Instagram has restricted the redirect URIs to be starting only with http:// or https:// while disabling scheme based URIs, how would we be using this code:  [[OLInstagramImagePickerController alloc] initWithClientId:@"YOUR_CLIENT_ID" secret:@"YOUR_CLIENT_SECRET" redirectURI:@"YOUR-APP-SCHEME://instagram-callback"];?

Does that means the library needs an update?

**Comment by raheelsadiq** [comment]
I am also stuck on this, how did you resolve it
