### ISSUE TITLE
Login View is Black

### ISSUE THREAD

**Issue by meandkareem** [OceanLabs/InstagramImagePicker-iOS#3]
I added this pod in ios 8.3 app and all I can see is black view on login .

**Comment by dbotha** [comment]
@meandkareem Sorry about that, does the Sample app work for you when you bump the deployment target to 8.3? I just tried and it appears to work just fine.

**Comment by piotrros** [comment]
I have the some problem! The same thing happens on your facebook image picker. Only black background with navigation bar... Example works fine on sdk 8.4. Is it maybe some conflict with swift (yes I use swift)? Please help :)

**Comment by piotrros** [comment]
Fixed the problem. First of all I removed !use_frameworks from Podfile. Then I created my own objc-swift bridge. I also had to modfiy Podfile again:

pod 'NXOAuth2Client', '~> 1.2.8'
pod 'UIColor-HexString'
pod 'SDWebImage', '~> 3.7.2'
pod 'InstagramImagePicker'

I had to specify versions (got them from example).

**Comment by iOSCowboy** [comment]
Fix for this issue: https://github.com/OceanLabs/InstagramImagePicker-iOS/pull/7

Same fix should be applied to the Facebook library, @piotrros.

Ping @dbotha
