### ISSUE TITLE
Single image selection?

### ISSUE THREAD

**Issue by magnett** [OceanLabs/InstagramImagePicker-iOS#4]
Hi & thanks for this library!
I see no obvious way to avoid multiple image selection. Right?
If so, it would be useful to able to do just that...single image selection...

**Comment by kkarayannis** [comment]
There is currently no direct way to set that, however you can achieve what you require with the following workaround:
https://github.com/OceanLabs/FacebookImagePicker-iOS/issues/5

That image picker is essentially the same as this one, but for Facebook.

**Comment by magnett** [comment]
I did that already, but it would be nice to exposed. I am using the cocoapods version and this kind of dirty fixes can ruin your day in no time...
Anyway, ευχαριστώ πολύ!

**Comment by kkarayannis** [comment]
This is now supported. Take a look at "Set maximum number of selections" in the documentation.
https://github.com/OceanLabs/InstagramImagePicker-iOS/blob/master/README.md#sample-apps
