### ISSUE TITLE
Not working on iOS 9

### ISSUE THREAD

**Issue by piotrros** [OceanLabs/InstagramImagePicker-iOS#6]
Hi, I've just updated my app to ios 9 / xcode 7. After that this library stopped working. I have latest version from cocoa pods. After simple debugging in function 'fetchMediaForAccount' NXOAuth2Request is returning nil response and response data. And it also contains error, but a strange one:

```
(NSError *) error = 0x005b188c domain: class name = __NSStackBlock__ - code: 364771328
```

When compiled on xcode 6.4 it works without any problem on ios 9.

**Comment by kkarayannis** [comment]
Same issue and solution as the Facebook picker:
github.com/OceanLabs/FacebookImagePicker-iOS/issues/11

Only you need to unblock the following domains:
akamaihd.net
facebook.net
instagram.com
fbcdn.net
cdinstagram.com

**Comment by piotrros** [comment]
Thanks. Your list is almost perfect, but you made a typo in last name, it's "cdninstagram.com". With this it's working.
