### ISSUE TITLE
How can my selected image from instagram, being selected when i represent "OLInstagramImagePickerController" ?

### ISSUE THREAD

**Issue by microdevil** [OceanLabs/InstagramImagePicker-iOS#8]
Hi....
Beforehand, i'd like to say thanks for this pods, because this pods help me to create my own application.
However, i have found problem from this pods. The problem i have is my selected image from instagram, not being selected when i represent "OLInstagramImagePickerController". Could you tell me how my selected image from instagram, being selected when i represent "OLInstagramImagePickerController" ?
Thanks...

**Comment by dbotha** [comment]
Hi @microdevil , use OLInstagramImagePickerController.selected property: https://github.com/OceanLabs/InstagramImagePicker-iOS/blob/master/InstagramImagePicker/InstagramImagePicker/OLInstagramImagePickerController.h#L84

**Comment by microdevil** [comment]
Hi @dbotha 
Thanks for your answer. Unfortunately, that was not solving my problem.
I am trying change the property code from 

```
@property (nonatomic, copy) NSArray/*<OLInstagramImage>*/ *selected;
```
to be 

```
@property (nonatomic, copy) NSArray <OLInstagramImage>  *selected;
```
But, it is not working. My Xcode give me error warning like this 

![screen shot 2015-11-02 at 5 17 56 pm](https://cloud.githubusercontent.com/assets/3820278/10879472/c9d22ac2-8186-11e5-860c-a5932b91fde3.png)

Could you let me know what's wrong with my code ?

Thanks....

**Comment by dbotha** [comment]
Hi @microdevil , don't uncomment the `/*<OLInstagramImage>*/`, I just had that there to let you know that the objects in the NSArray should be of type `OLInstagramImage` and not some other type. If you ensure the objects are `OLInstagramImage` you shouldn't have a problem.
